pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

edpartchelbel:
    resource: "@EdpartchelbelBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
